service: cart-service

frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: dev

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
